"""test_imports

Revision ID: 5277021a51cf
Revises: b19c6cf9b3a9
Create Date: 2020-03-26 12:27:27.142476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5277021a51cf'
down_revision = 'b19c6cf9b3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
